Adds helper text
jupyter-server/jupyter-scheduler pull request #143
Opened 2022-10-12 23:52 UTC by jweill-aws

Fixes #94. Adds helper text to "Output path" input.

![image](https://user-images.githubusercontent.com/93281816/195468366-2c90d28f-ba1e-4c6c-a122-cbf82d6ae2a6.png)

2022-10-14 17:59 UTC, ellisonbg commented
Question for @3coins on the backend. Is the output prefix:

a. The path of output files relative to the input file?
b. The path relative to the root of the Jupyter Server?
c. The absolute path on the file system?
d. A combination of any of the above?

2022-10-15 21:10 UTC, 3coins commented on src/mainviews/create-job.tsx
> +              'Relative path where output files are written'
```suggestion
              'Output directory where job output files are written, default is same directory as input file'
```

2022-10-15 21:11 UTC, 3coins commented
> Question for @3coins on the backend. Is the output prefix:
> 
> a. The path of output files relative to the input file? b. The path relative to the root of the Jupyter Server? c. The absolute path on the file system? d. A combination of any of the above?

Answer is b) The path relative to the root of the Jupyter Server

2022-10-16 23:58 UTC, ellisonbg commented
Do we accept paths with a leading `.` or `..`? If the path is always relative to the server root, we should show the path relative to the input notebook.

2022-10-17 20:07 UTC, dlqqq commented
From 10/17/2022 standup:

1. Let's consider renaming "output path" to "output directory" in the UI while we're at it. Paths can refer both to directories and regular files, so let's make our intentions explicit for clarity.

2. We should add a "home" icon with a forward slash to the left of the output directory input to further emphasize that the path must be relative to the server root. @ellisonbg Please confirm.

2022-10-17 20:09 UTC, dlqqq requested changes

2022-10-17 20:09 UTC, dlqqq commented on src/mainviews/create-job.tsx
> +              'Relative path where output files are written'
Believe a more helpful helper text would be: "Path to directory in which output files will be written. Path must be relative to the server root." @ellisonbg Thoughts?

2022-10-19 21:14 UTC, jweill-aws commented
Per @ellisonbg's feedback, sets the default output directory to the input file's directory. Relies on the invariant in `path` that directories are delimited with `/`.

2022-10-19 21:15 UTC, jweill-aws commented on src/index.tsx
> +function getSelectedFileName(widget: FileBrowser | null): string | null {
These now appear in the same order in which they're called below.

2022-10-20 17:00 UTC, ellisonbg commented
Can you post a screenshot of the current state of this PR? Here are the main points I want to make sure we are covering:

* The Input file should show the path of the input file, not just its name.ext.
* The default value of the output directory (let's call it that in the UI) should be the path of the input file.
* To emphasize to users that these paths are relative to the server root, we should render a `:home: / ` to the left of the input file and output directory as the home icon is used in JupyterLab to indicate the server root directory.

2022-10-20 17:56 UTC, dlqqq requested changes
This looks great! Really close to what we want. Just two more things:

1. We would like to have a home icon followed by a forwards slash to the left of all input fields that accept relative paths to the server root, i.e. "input file" and "output directory".

2. Could you add a forwards slash to the output directory input value to further emphasize that it's a directory? For example, in the below screenshot, it should say "outputs/". The backend should be able to handle this redundant forwards slash, but please test it out as well when you make this change.

<img width="521" alt="Screen Shot 2022-10-20 at 10 52 24 AM" src="https://user-images.githubusercontent.com/44106031/197022829-7e6b2f7b-9e34-4441-81c0-8b7b6bb068e9.png">

2022-10-20 18:56 UTC, jweill-aws commented
> To emphasize to users that these paths are relative to the server root, we should render a `:home: / ` to the left of the input file and output directory as the home icon is used in JupyterLab to indicate the server root directory.

@ellisonbg Should the ":house:/" be rendered to the left of the outlined "Output directory" `TextField` or should it be _inside_ the input area?

2022-10-20 19:19 UTC, ellisonbg commented
Nice! I think putting the home icon inside the text field is nice. Also, let's add it to the input file text field as well.

2022-10-20 19:20 UTC, ellisonbg commented
Also, let's make sure to render these things in a similar way in the detail view.

2022-10-20 19:24 UTC, jweill-aws commented
Here's what the UI looks like with the :house: adornment in both text fields

![image](https://user-images.githubusercontent.com/93281816/197039328-88ea1666-1d8f-4138-b7aa-01b4bf5d5b5d.png)

2022-10-20 19:28 UTC, jweill-aws commented
… and in the detail view:

![image](https://user-images.githubusercontent.com/93281816/197040146-642aa4d0-a75a-422f-ac69-c594ead92329.png)

2022-10-21 17:01 UTC, merged