Disable create on submit
jupyter-server/jupyter-scheduler pull request #186
Opened 2022-10-22 18:47 UTC by jweill-aws

Fixes #179. On submission, replaces the "Create" button with a progress indicator. If the job succeeds, the user is brought to the list page. If the job fails, the user remains on the create page and the "Create" button becomes visible again.

In the video below, the "Create" handler introduces a 5-second delay and approves the job only if its name contains `ok`.

https://user-images.githubusercontent.com/93281816/197357569-7a6eb8c2-0713-4f2a-a092-637879d2dca7.mov

2022-10-22 19:58 UTC, jweill-aws commented
Updates PR to hide both "Cancel" and "Create", since if create takes a long time, a user might try to click "Cancel," but this will not actually cancel the job creation request.

2022-10-23 15:41 UTC, ellisonbg requested changes
Overall this looks good. I think it does make sense to remove the Cancel and Create buttons. A few minor comments:

* I think we should put a small descriptive text next to the spinner. Something like "Creating job..." or "Creating job definition...".
* What happens if the user closes the panel while the job is being created and job creation fails? I guess there won't be any record of that job? We should probably open an issue to discuss how to handle this case.

2022-10-23 19:59 UTC, jweill-aws commented
@ellisonbg Added descriptive text to display beside the spinner. Opened #190 to handle asynchronous job creation errors.

2022-10-24 16:38 UTC, andrii-i approved these changes
Looks and works well, significantly improves usability.

I'd consider putting spinner in the middle of the screen to be in line with how it is usually used vs right but this is a subjective preference.

2022-10-24 16:58 UTC, dlqqq commented
Why not just having the loading spinner render inside the "Create" button itself and then disable both the create and cancel buttons? This would allow you to keep roughly the same layout and avoid confusing the user by "flashing" a UI change.

2022-10-24 21:15 UTC, merged