WIP: Create job from job definition
jupyter-server/jupyter-scheduler pull request #227
Opened 2022-10-29 00:26 UTC by jweill-aws

WIP change for #209. Also fixes #225.

On the Job Definition Detail page, adds a "Run Job" button that brings the user to a minimal version of the Create Job form that displays only the job definition ID and lets the user edit parameters. **The API to create a job this way is not yet available.**

Demo video:

https://user-images.githubusercontent.com/93281816/198753293-50c90be5-7e93-4307-879a-0ccb52816195.mov

2022-10-29 19:11 UTC, ellisonbg commented
Overall, looks good. Wondering if we might want to name the action "Run job now" to emphasize that this is different from running it on a schedule. Also, the API in #228 will only allow users to set parameters, so we should hide the Additional options in this form. Also, will this form have the same job creation error handling as the normal create job (show the spinner, hide the buttons, show the error banner)?

2022-10-29 19:47 UTC, jweill-aws commented
I hesitated to use the word “now” because the button doesn’t take an immediate action, but rather brings the user to a form. (Perhaps “Run Job…” or “Run Job Now…” would be better.)

The button hiding behavior and error handling is the same as in the ordinary create job/JD form.

Sent from my iPhone

On Oct 29, 2022, at 12:12 PM, Brian E. Granger ***@***.***> wrote:

﻿

Overall, looks good. Wondering if we might want to name the action "Run job now" to emphasize that this is different from running it on a schedule. Also, the API in #228<https://github.com/jupyter-server/jupyter-scheduler/pull/228> will only allow users to set parameters, so we should hide the Additional options in this form. Also, will this form have the same job creation error handling as the normal create job (show the spinner, hide the buttons, show the error banner)?

—
Reply to this email directly, view it on GitHub<https://github.com/jupyter-server/jupyter-scheduler/pull/227#issuecomment-1295941426>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AWHV4GBJNTTODLLEDMF5V33WFVZGLANCNFSM6AAAAAARRQX3MA>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-10-31 18:54 UTC, jweill-aws commented
(Apologies for the botched non-rebase; I hadn't set up Git properly on my new computer yet)

Updates this change to remove advanced options from the run-from-JD form. Still WIP because no API is available yet.

![image](https://user-images.githubusercontent.com/93281816/199087058-216671cc-3647-45f8-9930-1259e1ae4ace.png)

2022-10-31 22:22 UTC, jweill-aws commented
This change is blocked until #228 is merged.

2022-11-01 16:17 UTC, 3coins commented
Request payload seems incorrect here, so passed parameters are not assigned. The payload should match the `CreateJobFromDefinition` model.
https://github.com/jupyter-server/jupyter-scheduler/blob/9dd885c967c98ee9bceb8046c066d1b2e5411de5/jupyter_scheduler/models.py#L272-L273

2022-11-01 16:20 UTC, 3coins requested changes

2022-11-01 17:02 UTC, 3coins approved these changes

2022-11-01 17:06 UTC, merged