Check for and remove "RTC" drive prefix when returning selected file path added by the jupyter-collaboration
jupyter-server/jupyter-scheduler pull request #541
Opened 2024-08-28 17:49 UTC by andrii-i

## References

Fixes #429 

## Code changes

`getSelectedFilePath` helper function now uses serviceManager.contents API to check if there is an added "RTC" drive name in the file path and removes it 

## User-facing changes

Jupyter Scheduler now works when `jupyter-collaboration` is installed.

## Backwards-incompatible changes

None

2024-08-28 18:05 UTC, dlqqq requested changes

2024-08-28 18:05 UTC, dlqqq commented on src/index.tsx
> +      console.log(filePath);
Can this console log statement be removed?

2024-08-29 13:57 UTC, dlqqq commented
@andrii-i Can you also post a link to the JupyterLab PR that provided the `getLocalPath()` reference implementation as a comment on this PR?

2024-08-29 16:44 UTC, andrii-i commented
@dlqqq thank you for looking into this. I added links to reference PRs into the PR description.

2024-08-29 19:20 UTC, sravyasdh commented
Tested in both Sagemaker Studio private and shared spaces, the fix works great.

2024-08-29 19:26 UTC, andrii-i commented
Thank you everyone for looking into this.

2024-08-29 19:27 UTC, merged